### ISSUE TITLE
Add Working() method to get current number of  busy goroutines

### ISSUE THREAD

**Issue by czs007** [panjf2000/ants#254]
**Is your feature request related to a problem? Please describe.**
We need to know how many goroutines are currently executing the task function.

Currently, 
Capacity indicates the capacity of the pool;
Running indicates the number of live goroutines;
Free is  Capacity minus  Running.

I suggest adding `Working() int` and `Idle() int`.

Working means the number of  buy goroutines and Idle() indicates the number of  idle  goroutines.

**Describe the solution you'd like**

I would likt  to add the atomic variable `working`,  add 1 before executing the task fuction f(), and decrease it by 1 after the execution.

Working() int   return the atomic value `working`.
Idle() is Running() - Working().

**Comment by panjf2000** [comment]
Incrementing an atomic variable before every task is executed and decreasing it after the task is done, seems like a non-trivial cost, and I suppose this is not a very general case, therefore, it doesn't look like a good idea to me that the majority will have to pay for the negative impact of performance just because of some scenarios of the minority.

Besides, if I understand you correctly, you can achieve this requirement by putting these atomic operations in your task function submitted to the pool.

**Comment by czs007** [comment]
@panjf2000  OK.  I use other methods to achieve this requirement.
